### ISSUE TITLE
Not overclocking on Pi 4

### ISSUE THREAD

**Issue by jjosephliu** [Cat5TV/pinecraft#14]
I followed all instructions on the video but when i run vcgencmd and sysbench it keeps on telling me that the gpu freq is topped at 1.5ghz.
Unless I was mistaken, I'm prettu sure the video said it  would overclock to 1.9 automatically.

Cheers

**Comment by Cat5TV** [comment]
Thanks for reporting this. As it turns out, Ubuntu Server IOT has placed the config.txt in /boot/firmware (rather than /boot). I will issue a patch soon. Meanwhile, you could "patch" your own server with `cat /boot/config.txt | sudo tee -a /boot/firmware/config.txt` until I issue the patch, which will append the contents of /boot/config.txt to /boot/firmware/config.txt. A reboot will be necessary for the changes to take effect. Please make sure you stop your Minecraft server safely first.

**Comment by Crito02** [comment]
Spent a day pulling my hair out with this same issue lol, came here to report the solution and can see I should have looked as soon as I saw the issue.  My fix was putting the settings in /boot/firmware/usercfg.txt (its the file left to place those commands).  Now my question is, the config.txt file that is timestamped and put away by the installer has ALOT of stuff in it.  Is the ubuntu server going to run ok without it?

**Comment by jjosephliu** [comment]
> Spent a day pulling my hair out with this same issue lol, came here to report the solution and can see I should have looked as soon as I saw the issue. My fix was putting the settings in /boot/firmware/usercfg.txt (its the file left to place those commands). Now my question is, the config.txt file that is timestamped and put away by the installer has ALOT of stuff in it. Is the ubuntu server going to run ok without it?

Yeah it'll be fine, its just a backup

**Comment by Cat5TV** [comment]
Just a note that this bug was fixed in Pinecraft 3.0, and also the overclocking settings no longer clobber the existing config file but either update it or append to it.
