### ISSUE TITLE
Will you add an new Cores for server?

### ISSUE THREAD

**Issue by ThEnchanted** [Cat5TV/pinecraft#40]
Could you add new cores for severing like Airplane and Patina
You could ask "why those cores why not keep cores like paper?" What are these cores newer heard about those
Answer: They are not that popular, those 2 cores (Airplane and Patina) have fewer vulnerabilities (Or even don't have) and are more stable had more settings

**Comment by Cat5TV** [comment]
I take requests, but there really needs to be a reasonable level of demand for each since it takes a lot of maintenance to ensure each server flavor works well. Usually, requests are submitted via YouTube comments, and I pay the most attention to comments that provide details (E.G., reason for the request) and especially those that spark a discussion with the community (E.G., other viewers concurring with the request. You're also welcome to provide a PR if you want to code it.
