### ISSUE TITLE
How to change manually change Minecraft Version

### ISSUE THREAD

**Issue by Sharktail100** [Cat5TV/pinecraft#49]
hello,
I was wondering how I would change the version from the default 1.18.1 Forge to 1.12.2 forge. I have tried to manually change by simply  deleting the 1.18.1 then switch it it out for 1.12.2, i did the `./minecraft/server` show up with this
![image](https://user-images.githubusercontent.com/65730280/147836850-c52c52b5-6512-44a8-984b-010b78b037b7.png)
So am I doing wrong or something?

Thanks,
Alex

**Comment by Cat5TV** [comment]
At present, Pinecraft's goal is to ensure you have the latest version of the chosen Minecraft server. Your desire to run Forge 1.12 suggests Pinecraft Installer is probably not for you. Forge 1.12 will only run on Java 8 as it is extremely old. As you can see in your screenshot, Pinecraft Installer has set you up with Java 17. If you're serious about wanting to run such an old server, be sure to verify first that they have patched that version against the Log4j exploits.

Closing since this has nothing to do with Pinecraft but rather is a Forge 1.12 question.
