### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by bargy73** [Cat5TV/pinecraft#6]
Thanks for all your work, I keep getting Black flagged during the Java install, Wants me to install the latest JRE to continue.
Tried that a few times but the latest Java JDK is 11. With other installs I have tried, it wants Java16 I think?
![2021-06-19](https://user-images.githubusercontent.com/9423318/122624294-e3ebcd80-d0e2-11eb-8578-36924d2b6882.png)

**Comment by eyoung100** [comment]
The default JDK required is 16.  Please read the front page  RE: Ubuntu

**Comment by bargy73** [comment]
> The default JDK required is 16. Please read the front page RE: Ubuntu

Thanks will give that a go.

**Comment by Cat5TV** [comment]
Please follow the directions in the README.

**Comment by bargy73** [comment]
Thanks Robbie 
Yep follow it and working now thankyou 

Started it once but crashed trying again later to see what the issue is

Cheers Jack

**Comment by Cat5TV** [comment]
@bargy73 more times than not when I hear of this issue, it's because the user is running a distro that has a desktop environment running, or other software installed and using RAM (it happens when the Minecraft Server runs out of RAM, which is why you can't use a Desktop Environment, which uses a lot of it).

My suggestion is for you to join the Discord server if you haven't already done so, since you can more easily discuss any minor issues you experience. If you find a problem with Pinecraft, please open another issue here on Github, but for discussion, Discord is the best spot.

Cheers,
Robbie

**Comment by bargy73** [comment]
Yer that was my thoughts exactly 
I’m also going to clone the SD card to SSD to see if that helps
