### ISSUE TITLE
Server overloaded

### ISSUE THREAD

**Issue by InflictedRhyno** [Cat5TV/pinecraft#72]
hi,
I just installed pinecraft on a Pi4 8Ram ,for now on a 32GB class 10 SD card
I managed to get online but after a few minutes is see "Can't keep up! is the server overloaded?
So i'm afraid it will crash wen i got 4 people online. 
is it because of the 32GB card ?

and i heard that the game is already lagging on a local server with 2 ppl playing so is there a way to boost up RAM ?

Greetz Greg

**Comment by Pharaoh-2398** [comment]
Yeah, same with me too. I'm using a 64 bit OS on a 8 GB raspberry PI 4, but the pinecraft installer did not give me full ram usage. Hence, I'm getting the same thing. Is there any way to manually increase ram allocation?

**Comment by Cat5TV** [comment]
I've covered this in a few of the Pinecraft videos. It's not an "issue" per se. Just [observe the README where it specifically talks about number of players](https://github.com/Cat5TV/pinecraft/#compatibility-tests). The tick keep up "issue" is your storage media unable to keep up, but is only a problem if you actually experience lag (it's by design and not a problem unless you experience lag). If you find your server is lagging, follow the instructions in the videos I've provided (such as [the Top 5 FAQ video](https://www.youtube.com/watch?v=4YgS5M4t_Qg)) that specifically show how to upgrade your storage to keep up. Have fun!
