### ISSUE TITLE
Change Port Used

### ISSUE THREAD

**Issue by KilometerDev** [Cat5TV/pinecraft#87]
Is there a way to change the port that the server uses? If so, how would I do that on my lite OS, I'm not very familiar with the commands yet as this is one of my first projects with it.

**Comment by AriTedeschi** [comment]
Yes, there is
You can do it after or before the installing

Before installing:
Right after you clone the project, inside "/pinecraft/assets" folder there is an "server.properties" file which is a configuration file.
Within it you can set the property ["query.port"](https://github.com/Cat5TV/pinecraft/blob/main/assets/server.properties#L12) to another port which is not on use

After installing:
Right after you installed the server, insede "/home/yourUser/minecraft" there is an "server.properties" file which is a configuration file.
Within it you can set the property "query.port" to another port which is not on use.

Advices.:
Shutdown the server before changing the door otherwise it will not be applied;
Avoid setting the port as 8080,8081, 808X generally they are reserved ports

**Comment by AriTedeschi** [comment]
Yes, there is
You can do it after or before the installing

Before installing:
Right after you clone the project, inside "/pinecraft/assets" folder there is an "server.properties" file which is a configuration file.
Within it you can set the property ["query.port"](https://github.com/Cat5TV/pinecraft/blob/main/assets/server.properties#L12) to another port which is not on use

After installing:
Right after you installed the server, insede "/home/yourUser/minecraft" there is an "server.properties" file which is a configuration file.
Within it you can set the property "query.port" to another port which is not on use.

Advices.:
Shutdown the server before changing the port otherwise it will not be applied;
Avoid setting the port as 8080,8081, 808X generally they are reserved ports

**Comment by Cat5TV** [comment]
What is the purpose in this request? You would typically change the port on your NAT. There is no need to change it on the DST (Pinecraft Server in this case) since you can only run one Minecraft server per Pinecraft server.
